apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cf-kafka-rest.fullname" . }}
  labels:
    {{- include "cf-kafka-rest.labels" . | nindent 4 }}
data:
  kafka-rest.properties: |
    {{ .Values.kafka_rest.properties | nindent 6 }}


  log4j.properties: |
    log4j.rootLogger=INFO, stdout, file

    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c:%L)%n

    log4j.appender.file=org.apache.log4j.RollingFileAppender
    log4j.appender.file.maxBackupIndex=10
    log4j.appender.file.maxFileSize=100MB
    log4j.appender.file.File=/var/log/kafka-rest/kafka-rest.log
    log4j.appender.file.layout=org.apache.log4j.PatternLayout
    log4j.appender.file.layout.ConversionPattern=[%d] %p %m (%c)%n
