apiVersion: v1
kind: Service
metadata:
  name: {{ template "cf-kafka-rest.fullname" . }}
  labels:
    {{- include "cf-kafka-rest.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: rest-proxy
      port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP  
  selector:
      {{- include "cf-kafka-rest.selectorLabels" . | nindent 4 }}
